### ISSUE TITLE
Bug ? nvim-gtk only works if is launched from a console

### ISSUE THREAD

**Issue by Zardoz89** [daa84/neovim-gtk#102]
This a bit weird... I have nvim-gtk isntalled on /usr/local/ and I have a .desktop file pointing to it.
I noticed that (I could check since what commit this is happening), I launch nvim-gtk from the desktop menu or the app launcher, the gui isn't show. However, doing a "ps aux | grep nvim" shows the nvim-gtk process but not nvim process.

Even I try to launch nvim-gtk directly from krunner using the path to the nvim-gtk executable. Same thing.
Looks that nvim-gtk only works correctly if I launch it from the console.

PD: I verified that this is happening with the last commit ( f7ee2ea3d89af59e57f956f5b68f173e0ace1ee7 ), and was happening on the commit ( bda35efe8810f7cfab9c56778f9dd7cb066425c2 )

**Comment by Zardoz89** [comment]
I managed to workaround creating a bash script that launches nvim-gtk and using it to launch it from the DE launcher/menu.

**Comment by daa84** [comment]
This is some kde launcher thing, it creates std input that check by isatty as not tty. Looks like same as #91

**Comment by Zardoz89** [comment]
This happens with Eclipse. I have it config to launch nvim-gtk. The funny thing is that the bash script trick, not fixes it! If I try to do a kill to the bash script, suddenly nvim-gtk pops up.
Also, I noticed that when I close eclipse, suddenly all nvim-gtk instances pops up.
