### ISSUE TITLE
pass params to nvim, not only files

### ISSUE THREAD

**Issue by Zardoz89** [daa84/neovim-gtk#103]
Would be interesting that nvim-gtk pass the "-c {command}", "-cmd {command}" "-d", "-R" and "-x" to nvim. They are useful, for example to allow to launch nvim-gtk from some IDE or other tools, like git mergetool

On my case, i'm trying to indicate to nvim that auto do a ":cd %:p:h" ONLY when I launch it from eclipse. And this would far more easy if I can use "-c" option.

**Comment by daa84** [comment]
is PR #101 is what you looking for?

**Comment by Zardoz89** [comment]
Yep!
