### ISSUE TITLE
Can't pass commands via `nvim-gtk +COMMAND`

### ISSUE THREAD

**Issue by fgrsnau** [daa84/neovim-gtk#104]
Usually, vim evaluates commands provided by the `+` switch. This also works for gvim and nvim-qt for example.

Can this behaviour be implemented in nvim-gtk?

Edit: nvim-qt implements this by simply forwarding additional arguments to nvim.

**Comment by daa84** [comment]
you can pass addition arguments to nvim with `--`

**Comment by fgrsnau** [comment]
Can you provide some example? As far as I can see this is not really documented anywhere.

The following command does not work for me: `nvim-gtk -- "+set tw=72 fo+=aw"`
It just opens a buffer for the file `+set tw=72 fo+=aw`.

**Comment by daa84** [comment]
This is latest PR merge, new feature 😃 
https://github.com/daa84/neovim-gtk/wiki/Configuration#command-line

**Comment by fgrsnau** [comment]
Oh, I built neovim-gtk shortly before this PR got merged. This works as expected now! :)
