### ISSUE TITLE
Flatpak version does not load user configuration files

### ISSUE THREAD

**Issue by sebastien** [daa84/neovim-gtk#106]
At the moment neither `~/.config/nvim/ginit.vim`, `~/.config/nvim/init.vim` or `~/.config/nvim-gtk/ginit.vim`, `~/.config/nvim-gtk/init.vim` load using the latest Flatpak install (af8423f004bc5395a7c0b81844164317b4b490a7cac1a62dcc31c12b17ef4931) on Fedora 28.

Is there any way I can get the path of the configuration file used by nvim-gtk?

**Comment by daa84** [comment]
It's on flatpak specific directory ~/.var/app/org.daa.NeovimGtk/config/nvim/
Think echo $MYVIMRC give it, not sure

**Comment by sebastien** [comment]
Thanks, but no it's actually not define `echo $MYVIMRC` in Vim yields nothing. Would you be open to update NeovimGtk so that it looks into `$HOME/.config/nvim/init.vim` for configuration first?

**Comment by daa84** [comment]
This path is standard of flatpak and passed to application via XDG_CONFIG_HOME by flatpak. So application nvim-gtk and nvim uses XDG_CONFIG_HOME variable.

**Comment by sebastien** [comment]
OK, makes sense, thanks!
