### ISSUE TITLE
Auto-complete does not popup automatically

### ISSUE THREAD

**Issue by sebastien** [daa84/neovim-gtk#107]
With the following `init.vim` and [minpack](https://github.com/k-takata/minpac) installed, the *completor* extension automatically pops-up the completion menu upon typing (open `nvim` type `hello hell`, the autocomplete popus up with `hello` as completion. This works in terminal `nvim` and `nvim-pygtk3`, but not int `neovim-gtk`.

```
silent! packadd minpac
call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})
call minpac#add('maralla/completor.vim')
packloadall
```

![image](https://user-images.githubusercontent.com/14598/40978142-d5d58a18-68a0-11e8-82d1-a5a284fb4df3.png)

**Comment by daa84** [comment]
For me it just works.
please check neovim version
Minimum supported neovim version: 0.2.2

**Comment by sebastien** [comment]
I'm also using neovim `0.2.2` and NeovimGtk 0.2.0 -- I compiled NeovimGtk from source and it does work, however the current 0.2.0 Flatpak version does not. Thanks for checking!
