### ISSUE TITLE
No cursor nor bg color when NVIM_GTK_NO_HEADERBAR=1

### ISSUE THREAD

**Issue by cdevienne** [daa84/neovim-gtk#108]
When I start nvim-gtk with NVIM_GTK_NO_HEADERBAR=1, the cursor is not visible anymore, and all the bg colors too.

See the difference, here with the headerbar:
![nvim-gtk headerbar](https://user-images.githubusercontent.com/547135/41084743-436f8822-6a35-11e8-8110-b14883a8a221.png)

Without the headerbar:
![nvim-gtk noheaderbar](https://user-images.githubusercontent.com/547135/41084744-438d9c04-6a35-11e8-806b-b7df8e73e0f4.png)

**Comment by aq2** [comment]
try adding NVIM_GTK_DOUBLE_BUFFER=1 to your env variables

it worked for me, fwiw

**Comment by cdevienne** [comment]
Much better indeed! Thanks for the workaround!

**Comment by daa84** [comment]
Hm, looks like double_buffer needs to be enabled by default
