### ISSUE TITLE
Doesn't detatch from running console

### ISSUE THREAD

**Issue by hasufell** [daa84/neovim-gtk#111]
gvim used to detach from the running console. I think this is largely desired behavior, no?

**Comment by hasufell** [comment]
I have written a patch [here](https://gogs.hasufell.de/hasufell/neovim-gtk/commit/53cde1c2b8981a710c1218ca4e977bbfcb9f8f1b).

You can fetch it like this (sorry, I don't like github).

```sh
git fetch https://gogs.hasufell.de/hasufell/neovim-gtk.git daemonize
```

This utilizes the [unix-daemon](https://crates.io/crates/unix-daemonize) package.

**Comment by daa84** [comment]
Ok, looks good, but it must also be compiled on windows

**Comment by hasufell** [comment]
> Ok, looks good, but it must also be compiled on windows

Hmm, how do I test that it does? Just ifdef for linux?

**Comment by daa84** [comment]
it must be something like this https://github.com/daa84/neovim-gtk/blob/21e74c7ca7468a53ce1cbb449a19b8144f06836f/src/settings.rs#L26
`#[cfg(unix)]` on top of line or method just cut it from windows build
currently it does not build on windows

**Comment by hasufell** [comment]
branch updated, please fetch again and try

**Comment by daa84** [comment]
merged to master, thanks
