### ISSUE TITLE
Failed on Windows10

### ISSUE THREAD

**Issue by TillLindemann** [daa84/neovim-gtk#115]
I download the windows latest build,but when I hit the nvim-gtk.exe,it came out an error,said I lack the "libfribidi-0.dll",so I searched for this dll,and put it in the bin folder,then i hit the exe again,it came out with an application error: "the application can not launch normally(0xc000007b)"。I don't know how to fix it.

**Comment by daa84** [comment]
i use windows 10 and build it manually with msys2 environment. It can be that not all dlls copied from appveyor. Maybe need to fix build script.

**Comment by theFroh** [comment]
A likely cause. Here's what I get with my plain Win10 (not a touch of MSYS2):
```
---------------------------
nvim-gtk.exe - System Error
---------------------------
The code execution cannot proceed because libfribidi-0.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```

**Comment by daa84** [comment]
Does latest build fix this issue? Looks like new version of pango requires this library.

**Comment by theFroh** [comment]
Indeed it does! Nice job.
