### ISSUE TITLE
Hangs when syntastic marks a syntax error

### ISSUE THREAD

**Issue by VentGrey** [daa84/neovim-gtk#116]
Apparently when syntastic makes the program hang when it detects a warning or an error, console invoke does not throw any errors besides: `(NeovimGtk:20783): Gtk-WARNING **: Theme parsing error: gtk.css:6207:18: '-gtk-icon-filter' is not a valid property name
`
far from that the program works correctly. 

I'm using nvim v0.2.2 & nvim-gtk 0.2.0

**Comment by daa84** [comment]
What package do you use: flatpak or build from sources?
Can you try to run gdb and check backtrace?

**Comment by VentGrey** [comment]
I built from  sources with the instructions provided in the README.md file.
Backtrace shows the following:
`[New Thread 0x7fffeb5f2700 (LWP 9831)]
[New Thread 0x7fffe6bf9700 (LWP 9832)]
[New Thread 0x7fffe65ff700 (LWP 9834)]
[New Thread 0x7fffe5fff700 (LWP 9835)]
[New Thread 0x7fffe57fe700 (LWP 9836)]
[Thread 0x7fffe6bf9700 (LWP 9832) exited]
[Thread 0x7fffe5fff700 (LWP 9835) exited]
[New Thread 0x7fffe5fff700 (LWP 10001)]
[Thread 0x7fffe5fff700 (LWP 10001) exited]
[Thread 0x7fffe57fe700 (LWP 9836) exited]
[Thread 0x7fffe65ff700 (LWP 9834) exited]
[Thread 0x7fffeb5f2700 (LWP 9831) exited]
[Thread 0x7fffedb87700 (LWP 9829) exited]
[Thread 0x7ffff7fb4c00 (LWP 9825) exited]
[Inferior 1 (process 9825) exited normally]
`

**Comment by daa84** [comment]
I install syntastic plugin and still can't reproduce.
please try latest version from master.

If still reproducible, can you run debug version of application in gdb, something like this:
`gdb --args target/debug/nvim-gtk --no-fork`
and then in gdb shell
`bt full`

**Comment by VentGrey** [comment]
No error symbols  on gdb, latest commit install + a PlugUpdate seemed to fix the issue, maybe the issue was syntastic's thing since the plug update merged a lot of commits.
