### ISSUE TITLE
App exits on RMB click

### ISSUE THREAD

**Issue by unclechu** [daa84/neovim-gtk#117]
**Describe the bug**
When I just click right mouse button on _neovim-gtk_ window app exits. I can't see anything in log because it daemonized by default and I can't also see what `nvim-gtk --help` returns, because it is also daemonized and just exists with empty log, I wanted to see usage info by `--help` argument to disable daemonization.

**Technical information (please complete the following information):**
 - OS: Fedora 28 Workstation
 - Neovim version: NVIM v0.3.0
 - Neovim-Gtk build version: 5a6cc7d036631d6ed2b7934ff5d3a9e43a46fdf5

**Comment by davidsierradz** [comment]
I am experiencing the same behavior, when I click the mouse right button and then middle button, the app crashes, if I run nvim-gtk from a terminal with `nvim-gtk --no-fork` press the right and middle buttons this appears on the terminal:

```bash
thread 'main' panicked at 'already borrowed: BorrowMutError', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Uncaught panic, exiting
[1]    3264 abort (core dumped)  nvim-gtk --no-fork
```

**Technical information (please complete the following information):**
 - OS: Manjaro i3
 - Neovim version: v0.3.1-66-g3cc7462a0
 - Neovim-Gtk build version: 5a6cc7d

**Comment by daa84** [comment]
--help is a problem :smile:  don't know what to do with it. Need to think. There is two problems: 
1. is daemonize 
2. is that gtk-rs bindings does not support custom options that can be added.
