### ISSUE TITLE
nvim-gtk --help does nothing

### ISSUE THREAD

**Issue by Zardoz89** [daa84/neovim-gtk#118]
nvim-gtk --help don't show anything 
![imagen](https://user-images.githubusercontent.com/888483/41762360-b8a50e02-75fa-11e8-9037-fc3295661fc3.png)

Related to #117 

 - OS: kUbuntu 18.04
 - Neovim version: NVIM v0.2.2
 - Neovim-Gtk build version: d33acff

**Comment by keeferrourke** [comment]
It would be really helpful if command-line arguments could be documented.
