### ISSUE TITLE
[Feature Request] Vim airline topbar.

### ISSUE THREAD

**Issue by VentGrey** [daa84/neovim-gtk#119]
It would be nice to re-enable the vim-airline topbar when the env variable 
`NVIM_GTK_NO_HEADERBAR=1` is on so we could get a look like the image shown on the readme.md file :)

**Comment by Arvedui** [comment]
Just adding `call rpcnotify(1, 'Gui', 'Option', 'Tabline', 0)` should bring back the vim-airline topbar.

**Comment by VentGrey** [comment]
Thanks a lot! :D
