### ISSUE TITLE
Scrolling up or down flows (overwrite) the above or below screen characters

### ISSUE THREAD

**Issue by davidsierradz** [daa84/neovim-gtk#127]
**Describe the bug**
Open nvim-gtk with only vim-startify:

![1](https://user-images.githubusercontent.com/9190258/42904701-72beb392-8a9b-11e8-90b1-ce8a3e092576.png)

Scroll down with `j` or `<C-e>` (Notice the first `0` and second `0` replaces all characters below it):

![2](https://user-images.githubusercontent.com/9190258/42904706-75c21958-8a9b-11e8-8ed2-5acf31bf53c1.png)

If I press `<C-d>` or `zz` to move the screen position, the characters render correctly:

![3](https://user-images.githubusercontent.com/9190258/42904710-7806d028-8a9b-11e8-8aa6-da182ae5ab35.png)

Again press `<C-e>` or `j`:

![4](https://user-images.githubusercontent.com/9190258/42904713-7abe34be-8a9b-11e8-9024-aef8fd07c269.png)

Or `<C-y>` or `k`:

![5](https://user-images.githubusercontent.com/9190258/42904717-7d605ee0-8a9b-11e8-8fb0-adb59c8fcd53.png)

Check with relative numbers (the line number column):

![6](https://user-images.githubusercontent.com/9190258/42905458-b967a37e-8a9d-11e8-9cca-e66a2a9ae0c2.png)

**Technical information (please complete the following information):**
 - OS: Manjaro i3 17.1.11
 - Neovim version:
```
NVIM v0.3.1-1-g489d32f2b
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/yaourt-tmp-neuromante/aur-neovim-git-ninja/src/neovim-git-ninja/build/config -I/tmp/yaourt-tmp-neuromante/aur-neovim-git-ninja/src/neovim-git-ninja/src -I/usr/include -I/tmp/yaourt-tmp-neuromante/aur-neovim-git-ninja/src/neovim-git-ninja/build/src/nvim/auto -I/tmp/yaourt-tmp-neuromante/aur-neovim-git-ninja/src/neovim-git-ninja/build/include
Compiled by neuromante@neuromante-work-laptop

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
 - Neovim-Gtk build version: 2ebac955566b15ce2cdf41e6da9e2a50bea8659e (HEAD)

**Comment by unclechu** [comment]
I just was about to report the same issue, here is a small screencast of this issue:
![2018-07-19 01-52-32](https://user-images.githubusercontent.com/799353/42911467-750fc604-8b04-11e8-9708-adf62363306b.gif)

**Comment by unclechu** [comment]
It looks like it's fixed with 737a7c5.

**Comment by unclechu** [comment]
@daa84 This one appears again on 07284db.

**Comment by daa84** [comment]
Can it be because of unstable nvim?

**Comment by unclechu** [comment]
@daa84 I have stable one now from Fedora repo (`v0.3.0`), and this issue doesn't happen with 3ea809e

**Comment by unclechu** [comment]
I have two builds:
- *neovim-gtk-2018-08-01-3ea809e* - is okay
- *neovim-gtk-2018-08-10-07284db* - have this issue

**Comment by daa84** [comment]
How to reproduce it?
i try nvim-gtk -- -u NONE
then call set relativenumber
maybe some split or colorscheme or plugin?

**Comment by unclechu** [comment]
@daa84 I'm sorry, now I can't reproduce it. I'm starting to think I just created wrong symbolic link earlier, like to even older version of **neovim-gtk** (I have few built versions including a34d22d where this issue exists). Just ignore it, I let you know if I notice anything but for now let's think it's just my bad, I wasn't paying enough attention to what I'm doing.
