### ISSUE TITLE
Compilation error on Ubuntu 18.04: use of unstable library feature

### ISSUE THREAD

**Issue by keeferrourke** [daa84/neovim-gtk#129]
**Describe the bug**
`neovim-gtk` fails to build and install on Ubuntu 18.04 bionic with the following error after having installed all the required development dependencies:

```
make install
```

**ERROR**
```
cargo install --force --root /usr/local
  Installing nvim-gtk v0.2.0 (file:///home/keefer/Downloads/neovim-gtk)
   Compiling nvim-gtk v0.2.0 (file:///home/keefer/Downloads/neovim-gtk)
error[E0658]: use of unstable library feature 'swap_with_slice' (see issue #44030)
  --> src/ui_model/line.rs:35:38
   |
35 |         target.line[left..right + 1].swap_with_slice(&mut self.line[left..right + 1]);
   |                                      ^^^^^^^^^^^^^^^

error: aborting due to previous error

error: failed to compile `nvim-gtk v0.2.0 (file:///home/keefer/Downloads/neovim-gtk)`, intermediate artifacts can be found at `/home/keefer/Downloads/neovim-gtk/target`

Caused by:
  Could not compile `nvim-gtk`.

To learn more, run the command again with --verbose.
Makefile:10: recipe for target 'install' failed
make: *** [install] Error 101
```

**Technical information (please complete the following information):**
 - OS: Ubuntu 18.04 (Bionic Beaver)
 - Neovim version: `NVIM v0.2.2`
 - Neovim-Gtk build version: v0.2.2 (d174222d6df5e55887a09c299f91a9b1e7cac046)

**Comment by daa84** [comment]
please update rust compiler to latest stable version

**Comment by keeferrourke** [comment]
This is done using the latest available versions of `rustc` and `cargo` on Ubuntu 18.04..

**Comment by expl0ratory** [comment]
Latest on ubuntu 18.04 is 1.25, this requires 1.27, so you must ignore ubuntu, and install manually using https://www.rust-lang.org/en-US/ unfortunately

**Comment by daa84** [comment]
sorry, i don't support specific distributive rustc. Only requirement is use stable version. It is easy can be installed with rustup.
