### ISSUE TITLE
Feature request: Support for pasting the PRIMARY clipboard

### ISSUE THREAD

**Issue by wezm** [daa84/neovim-gtk#14]
It would be nice to be able to paste the [PRIMARY clipboard](https://specifications.freedesktop.org/clipboards-spec/clipboards-latest.txt) by pressing the middle mouse button or Shift-Insert.

**Comment by wezm** [comment]
I put a [$20 bounty on this](https://www.bountysource.com/issues/49732873-feature-request-support-for-pasting-the-primary-clipboard).

**Comment by daa84** [comment]
Now toolbar button paste CLIPBOARD and middle button paste PRIMARY mode. Also fix paste in command mode.
Shift-Insert not implemented as it can be binded with for example `nnoremap`.

**Comment by wezm** [comment]
Paste toolbar button is working for me but middle click only makes the mode cycle:

![peek 2017-10-13 09-42](https://user-images.githubusercontent.com/21787/31522695-eb031842-affa-11e7-8f34-90a79b539fcf.gif)

Tried middle button on mouse and laptop and both behave the same.

**Comment by daa84** [comment]
Can't reproduce,
does it work if just paste '*' register? in insert mode this is `Ctrl+r *` maybe you have some custom mapping on `Ctrl+r` ?

**Comment by daa84** [comment]
do some improvements, maybe this helps

**Comment by wezm** [comment]
I don't believe I have any mappings on `Ctrl-r`. You can see my [vim config](https://github.com/wezm/dotfiles/blob/master/vimrc) and [nvim config](https://github.com/wezm/dotfiles/blob/master/config/nvim/init.vim) in my dotfiles repo. I just tried the latest build on a different laptop (with the same config) and it worked!

**Comment by wezm** [comment]
I'll release the claim as soon as I can log into Bountysource. I'm getting an Internal server error when I try to log in at the moment.

**Comment by wezm** [comment]
Still can't log onto BountySource. I've [pinged them on Twitter](https://twitter.com/wezm/status/919432194132549632).

**Comment by daa84** [comment]
I also can't log onto BountySource
Thanks :+1:

**Comment by wezm** [comment]
I think I worked out how to trigger the behaviour in the animated GIF above. If you middle click in the space after the buffer it triggers this behaviour.

![screenshot from 2017-10-18 20-50-26](https://user-images.githubusercontent.com/21787/31712167-fe66e522-b445-11e7-8396-2df28536e466.png)

I.e. if the cursor is not on the last line and I middle click in the lower part of the window with the `~` lines it cycles through the different modes shown in the GIF.

**Comment by daa84** [comment]
still can't reproduce it, but found that neovim itself can process middle button 😄 , so just pass event directly to it. For me it do the same - paste from primary clipboard. maybe this helps.
If there is still problems, can you check this behavior without plugins loaded.

**Comment by last-partizan** [comment]
What about Shift+Insert? Maybe you can let nvim process it too?

When i enter EDIT mode and press Shift-Insert, it works as expected in plain nvim, but not nvim-gtk.
Also using Shift+Insert in command mode does not work, but works in plain nvim.

**Comment by daa84** [comment]
Looks like gnome termnal can process Shift+Insert and pass it to nvim
https://github.com/GNOME/vte/blob/be6cd8246c7993326677c9e2058deedac4263667/src/vte.cc#L5277

For gui - Shift+Insert already passed to nvim.
Maybe next maps can help:
```
map <S-Insert>		"*gP
cmap <S-Insert>		<C-R>+
imap <S-Insert>		<C-R>+
```
i don't test them, but think this must work.

**Comment by last-partizan** [comment]
None of that bindings works.

When i press Shift+Insert in command mode, nothing happens. But when i press Shift+Del, text <S-Del> is inserted.
So, i tried to bind <S-Del> and it inserts text from clipboard. Maybe Shift-Insert does not passed to gvim, and mus be handled like in gnome-terminal.

**Comment by daa84** [comment]
@last-partizan  yes, your right, Insert button does not passed, fixed this.
Also primary clipboard is `*`, so update mapping a bit
```
map <S-Insert> "*gP
cmap <S-Insert> <C-R>*
imap <S-Insert> <C-R>*
```

**Comment by last-partizan** [comment]
Now it works! Thanks!

**Comment by rbjorklin** [comment]
Did you ever get scroll/middle-click to paste?

Anyhow the remap mentioned above works for Shift-Insert! Maybe mention this in the README?
