### ISSUE TITLE
Ligatures are not shown

### ISSUE THREAD

**Issue by mcepl** [daa84/neovim-gtk#143]
**Describe the bug**
![Screenshot of the issue](https://user-images.githubusercontent.com/198999/45209372-21ae3d00-b28d-11e8-9c74-c239735e5b89.png)

So, I have set ``Fira Code`` as ``guifont`` (why nvim-gtk just doesn't honour that and forces me to do the silly things with ``~/.config/nvim/ginit.vim`` ;and is ``nvim`` or ``nvim-gtk``?), I have this in my ``~/.config/nvim/ginit.vim`` (according to [wiki](https://github.com/daa84/neovim-gtk/wiki/Configuration#user-content-configuration)):
```
if exists('g:GtkGuiLoaded')
    call rpcnotify(1, 'Gui', 'Font', 'Fira Code Medium 11')
endif
```

I have even set ``Fira Code`` as a system-wide font:

```bash
matej@milic: ~$ gsettings get org.gnome.desktop.interface monospace-font-name
'Fira Code Medium 11'
matej@milic: ~$
```
And still, there are no ligatures shown in my nvim-gtk. And frankly, ligatures are the only feature I miss from the in-console-neovim.

(The same happens with ``Iosevka`` font, just in case there would be doubt about the font itself).

**Technical information (please complete the following information):**
 - OS: Linux, OpenSUSE Tubmleweed current as of today
 - Neovim version: the latest build from HEAD (commit neovim/neovim@c0157e8fe)
 - Neovim-Gtk build version: the latest build from HEAD (commit b161bf8)

**Comment by SolidTux** [comment]
I also don't see ligatures with both Hasklig and Fira Code under Windows.

**Comment by saumyajyoti** [comment]
Ligatures did no work for me either on Windows with Fira Code and Iosevka.

**Comment by mcepl** [comment]
On the same computer, ligatures in gedit work (Fira Code), with neovim-gtk they don't.

**Comment by mcepl** [comment]
With my new build on https://build.opensuse.org/package/show/home:mcepl:neovim/neovim-gtk everything suddenly works. No idea, what has changed.

**Comment by mcepl** [comment]
![snimek z 2018-11-16 21-04-22](https://user-images.githubusercontent.com/198999/48644547-37558680-e9e3-11e8-8909-cf5851c5561b.png)

OK, so it is definitively weird. In one tab (with SPEC file for Linux RPM package) ligatures don't work (the result is the same as in the screenshot in the original description of this issue), whereas in the other tab with a Python file it does (ligatures ->, >= and ==).

**Comment by daa84** [comment]
This is because ligatures can not be rendered partly. When color of left side and right side is different. So in this case ligatures became just symbols

**Comment by mcepl** [comment]
OK, so this is NOTABUG. Thank you.

**Comment by mcepl** [comment]
@daa84 So, would you say that this is bug in syntax definition for SPEC files?

**Comment by daa84** [comment]
Don't think this is bug, it just not work with ligatures :)
I don't have idea why to draw on symbol with different color. Event if it possible with some special combination of layer merge operation, think it will look strange.
