### ISSUE TITLE
No window controls or menu items

### ISSUE THREAD

**Issue by corelon** [daa84/neovim-gtk#145]
**Describe the bug**
When the program starts I get no window controls (e.g. close, maximize, minimize or any menu items.
I can only see the side panel and the main Neovim window. Only way to close the program is by right clicking the icon on the taskbar. Even using :q on the last window does not close the program.
**Technical information (please complete the following information):**
 - OS: Windows 10
 - Neovim version: 0.3.1
 - Neovim-Gtk build version: latest from appveyor (downloaded 11 Sep)

**Comment by Arvedui** [comment]
Do you have NVIM_GTK_NO_HEADERBAR set?
If yes this is caused by #140 and my PR #144 should fix it.

**Comment by corelon** [comment]
I set it to 0 to see if it would make a difference, but it did not. Downloaded the latest from appveyor and it worked fine. Seems like to the PR fixed it indeed.
Thanks
