### ISSUE TITLE
Options after '--' not being passed into nvim

### ISSUE THREAD

**Issue by jtprince** [daa84/neovim-gtk#147]
This invocation opens `app.py` and then the file `--` as the next buffer (so, improperly interpreting `--` as a filename), and so does not set the variable as expected (since it interpreted as filename):

```
nvim-gtk app.py -- -c "let silliness=11"
# note that the command `:echo silliness` fails
# since options not passed in and silliness not set
```

This invocation merely opens the file named `--`, which also seems to be incorrect behavior:

```
nvim-gtk -- -c "let silliness=11" app.py
```

This command works as expected with nvim:

```
nvim app.py -c "let silliness=11"
# can `:echo silliness` and get abk 
```

### Technical information
 - OS: Arch
 - Neovim version: 0.3.1
 - Neovim-Gtk build version: arch pkg suggests it is v0.1.1-3

**Comment by daa84** [comment]
looks like arch pkg is old, not sure, i try with current version and for me it works

**Comment by jtprince** [comment]
Works as expected when using the `neovim-gtk-git` package, which compiles from source.  Thank you for checking this out.
