### ISSUE TITLE
The newly added guifont option behaves differently than Vim's version

### ISSUE THREAD

**Issue by baco** [daa84/neovim-gtk#158]
Vim's implementation of the option `guifont` supports a comma separated list of fonts to test, Neovim-GTK's version doesn't.

The `guifont` option in Vim supports having a list of fonts to test; if the first font listed is not available then it tries the second, and so forth until it finds one available or defaults on the system's default one.

When I tried this with Neovim-GTK, the editor failed to match the font trying to match the entire string, although the first listed font was available on the system. When I removed the trailing fonts in the list (from second to last), Neovim-GTK was able to load the font using the setting `guifont`.

**Technical information:**
 - OS: Linux Debian Sid
 - Neovim version: v0.3.2-826-g87d67814e
 - Neovim-Gtk build version: master version (7272a4ec02ee4d50f8686ad9257172518dadb375)

**Comment by daa84** [comment]
Not sure i use right way to search installed fonts, hope this works :smile:
