### ISSUE TITLE
Long terminal command causes window to resize

### ISSUE THREAD

**Issue by wezm** [daa84/neovim-gtk#16]
If you invoke a long terminal command, like those triggered by the [fzf vim plugin](https://github.com/junegunn/fzf.vim) the active tab's title becomes so wide that the window ends up becoming wider to fit it in.

![screenshot from 2017-09-26 17-04-16](https://user-images.githubusercontent.com/21787/30846963-0c80f6b8-a2dd-11e7-891a-ec965e3d73c5.png)

**Comment by daa84** [comment]
Current solution is to limit title length, maybe better one is available.
