### ISSUE TITLE
openSUSE/Fedora packages

### ISSUE THREAD

**Issue by mcepl** [daa84/neovim-gtk#160]
I have started packaging neovim-gtk for openSUSE (and by mistake also for Fedora/CentOS). It is available at https://build.opensuse.org/package/show/home:mcepl:neovim/neovim-gtk

Fedora building doesn't work, accepting all pull requests fixing the issue.

**Comment by daa84** [comment]
Good work :smiley: 
can you provide some small how to on how to install so i can put it with link to readme?

**Comment by mcepl** [comment]
(Click on "Download package")

**Comment by mcepl** [comment]
@kekePower yeah, https://github.com/neovim/neovim/issues/7879 seems to be too much alive to be closed, IMHO.

**Comment by mcepl** [comment]
@daa84 what would make this ticket to be closed? Pushing neovim-gtk to openSUSE/Factory?

**Comment by daa84** [comment]
added link to readme, 
@mcepl not sure about openSUSE/Factory as i am not opeSUSE user, if you think it is ok then you can close it 😄
