### ISSUE TITLE
requires gsed to install

### ISSUE THREAD

**Issue by braslau** [daa84/neovim-gtk#164]
Installing requires gsed (rather than standard sed). The Makefile should be modified to look for gsed and fall-back on sed (on systems where gsed is installed as sed).

**Comment by daa84** [comment]
Did the problem with `-i`. Think it is easier to replace `-i` with `> tmp && mv tmp original_file`?

**Comment by braslau** [comment]
Perhaps the `-i`?

sed:
     -i extension
             Edit files in-place, saving backups with the specified
             extension.  If a zero-length extension is given, no backup will
             be saved.  It is not recommended to give a zero-length
             extension when in-place editing files, as you risk corruption
             or partial content in situations where disk space is exhausted,
             etc.

gsed:
       -i[SUFFIX], --in-place[=SUFFIX]
              edit files in place (makes backup if SUFFIX supplied)


But I think that it is rather the s|search|replace| syntax (one would need to escape `\/` in `PREFIX` too)
