### ISSUE TITLE
Panic on startup: index out of bounds in src/ui_model/mod.rs

### ISSUE THREAD

**Issue by mklein994** [daa84/neovim-gtk#17]
I'm using rust stable. I can't reproduce this reliably, but for some reason, it crashes on startup, both with and without a file argument.

| Name | Details |
| --- | --- |
| Neovim version | Development version, from commit https://github.com/neovim/neovim/commit/43d32762e3aca2bf5656e0a928ac151f4702d93b |
| `rustup --version` | 1.6.0 (a11c01e8c 2017-08-30) |
| `cargo --version` | 0.21.0 (5b4b82ae 2017-08-12) |
|`rustc --version` | 1.20.0 (fd3d6973f4 2017-08-27) |
| Operating system | Arch Linux |

https://github.com/daa84/neovim-gtk/blob/0f4234a622d01b79fac4afd94e6561a15c68e1e8/src/ui_model/mod.rs#L76:25

Here's the backtrace. I installed it from the [AUR](https://aur.archlinux.org/packages/neovim-gtk-git), so that might explain why it's not showing other source code (it's not running from the same path it was built in):
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/ui_model/mod.rs:76:25
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: g_main_context_dispatch
  14: <unknown>
  15: g_main_context_iteration
  16: g_application_run
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: __libc_start_main
  21: <unknown>
```

EDIT: add neovim version

**Comment by daa84** [comment]
Fixed, if still have problems please comment here,
Thanks for report :smile:
