### ISSUE TITLE
Crash when displaying file in terminal

### ISSUE THREAD

**Issue by erlanger** [daa84/neovim-gtk#170]
**Describe the bug**
Running `head -23 s.qlf` with the attached file (on a terminal inside nvim-gtk) crashes nvim-gtk.
Decompress the attached file to replicate.

**Technical information (please complete the following information):**
 - OS: Linux
 - Neovim version: NVIM v0.3.2-1059-gfa5182489
 - Neovim-Gtk build version: v0.1.1-438-ga440248

[s.qlf.gz](https://github.com/daa84/neovim-gtk/files/2770270/s.qlf.gz)

**Comment by erlanger** [comment]
I guess you couldn't replicate?

**Comment by daa84** [comment]
no, it is fixed with above commit

**Comment by erlanger** [comment]
Tnx!
