### ISSUE TITLE
Bold text overlaps with the rest of the text

### ISSUE THREAD

**Issue by nbicalcarata** [daa84/neovim-gtk#174]
**Describe the bug**
Bold text overlaps with the rest of the text
![captura de pantalla de 2019-01-30 09-47-18](https://user-images.githubusercontent.com/5392962/51993954-6d989300-2475-11e9-8846-b70b223bffd1.png)

**Technical information (please complete the following information):**
 - OS: Fedora 29
 - Neovim version: 0.3.3
 - Neovim-Gtk build version: Commit 6c3af02

**Comment by daa84** [comment]
Looks like you use non monospaced font. Vim currently support only monospaced font because renderer is limited to grid.

**Comment by clason** [comment]
I have the same issue with Droid Sans Mono (definitely a monospaced font that works with neovim TUI and neovim-qt):
![image](https://user-images.githubusercontent.com/2361214/52115977-488c5780-2610-11e9-8295-92ceedab8591.png)

**Comment by calvin-evans** [comment]
@clason looks like it's related to ligatures, but not just any font with ligatures
e.g.

`:call rpcnotify(1, 'Gui', 'Font', 'Hack 12')` (no ligatures, works)
`:call rpcnotify(1, 'Gui', 'Font', 'FuraCode Nerd Font Mono 12')` (ligatures, doesn't work, also some of the ligatures, e.g. !== and ... look odd. This font works fine in other apps)
`:call rpcnotify(1, 'Gui', 'Font', 'Fira Code 12')` (ligatures, works. ligatures all work fine too)

**Comment by nbicalcarata** [comment]
I fixed it installing bold and italics missing font files, the issue is related to 'synthetic boldification' take a look here https://github.com/vhakulinen/gnvim/issues/84
