### ISSUE TITLE
Feature suggestion: Automatic checktime when window is focussed

### ISSUE THREAD

**Issue by wezm** [daa84/neovim-gtk#18]
Many years ago when I used MacVim, one of the benefits over console vim was that it automatically refreshed files when it regained focus. This can be great if you switch git branches or something then switch back. Instead of needing to remember to `:checkt` it does it for you.

**Comment by kirillrdy** [comment]
good idea, gvim does the same thing

**Comment by daa84** [comment]
Sounds good.
Solution maybe to add call of checktime on focus enter or implement autocommands FocusGained/FocusLost. So user can add something like this `autocmd FocusGained * checktime` to config.

**Comment by daa84** [comment]
Adding something like this to init.vim fix this problem
`autocmd BufEnter,FocusGained * checktime`
