### ISSUE TITLE
Key shortcut for the project view?

### ISSUE THREAD

**Issue by mcepl** [daa84/neovim-gtk#189]
**Describe the bug**
The point why I like vim is my pathological distrust to rodents. Could I have a way how to activate the Project View dialog without touching it?

**Technical information (please complete the following information):**
 - OS: Linux openSUSE (packages from https://build.opensuse.org/package/show/home:mcepl:neovim/neovim-gtk).
 - Neovim version: master of the git repo (https://github.com/neovim/neovim/commit/052ced4954075eca360ff7689afea82252f1c599).
 - Neovim-Gtk build version: master of the git repo (c089ef1de7a5e30172cd206101b26303c29fe420).

**Comment by daa84** [comment]
You can map NGToggleSidebar command to sortcut.

**Comment by mcepl** [comment]
``E492: Not and editor command: NGToggleSidebar``, but also I was mistaken, I don't need Sidebar, I meant the Open dialog.

**Comment by daa84** [comment]
Problem with commands looks same as in #181 . Think this is depends on installation/paths.
For open Open dialog there is no such command

**Comment by daa84** [comment]
New command NGShowProjectView
