### ISSUE TITLE
Feature request: ability to use ctermfg/ctermbg instead of guifg/guibg for colorschemes

### ISSUE THREAD

**Issue by unclechu** [daa84/neovim-gtk#190]
Add an ability to force using ctermfg/ctermbg colors instead of guifg/guibg. To kinda act as TUI in context of rendering colors.

I have some old colorschemes which look a lot better in TUI than in neovim-gtk GUI, I'd like to use neovim-gtk but be able to make neovim-gtk render such colorschemes as TUI does.

This option could be set via `rpcnotify` for example.

I've been asking about this in this main neovim's chat: [#neovim:matrix.org](https://riot.im/app/#/room/#neovim:matrix.org) and I've been told by _Justin M. Keyes_:
> see `:help ui-options`. The GUI can set `ext_termcolors` on attach, then ctermfg/ctermbg are used instead of guifg/guibg.
>
> You probably will need to patch the GUI or make a feature-request, since this is not a popular request. It's trivial for any GUI to support this, but probably most of them don't know about it.

**Comment by daa84** [comment]
`call rpcnotify(1, 'Gui', 'Option', 'Cmdline', 1)`
can you check it in termcolors branch?

**Comment by justinmk** [comment]
do you mean:

    call rpcnotify(1, 'Gui', 'Option', 'Termcolors', 1)

**Comment by daa84** [comment]
ups, yes Termcolors
`call rpcnotify(1, 'Gui', 'Option', 'Termcolors', 1)`

**Comment by unclechu** [comment]
@daa84 It seems it doesn't affect anything. I'm trying it with [solarized8](https://vimawesome.com/plugin/solarized-8) colorscheme. I was trying to set that option after I start __neovim-gtk__ and also in `init.vim`/`ginit.vim` before switching colorscheme.

Commit hash: `2b8149ba54afb6fc39021ea65a76f2c1d49b4c3e`

**Comment by justinmk** [comment]
Why not just check it yourself with a simple highlight command.

    hi Normal ctermfg=red guifg=green

**Comment by daa84** [comment]
I'll check, 
Maybe that this option works only on attach and not after...

**Comment by daa84** [comment]
1. this option supports only on nvim 0.4
2. also look like it works only on with new multi grid api

Think time to merge branch newgrid to master
then apply this changes to it

**Comment by unclechu** [comment]
But nvim 0.4.0 isn't exists yet, it's in development and isn't released yet. I could take months.

**Comment by daa84** [comment]
new branch termcolors_opt, option --cterm-colors must solve problem also on old version without option ext_termcolors
please check

**Comment by unclechu** [comment]
@daa84 It's working!

**Comment by unclechu** [comment]
@daa84 Will it be merged to master branch soon?

**Comment by daa84** [comment]
merged
