### ISSUE TITLE
Snap seems broken.

### ISSUE THREAD

**Issue by brown-d** [daa84/neovim-gtk#198]
**Describe the bug**
I installed the Snap but it doesn't work.

**Technical information (please complete the following information):**
 - OS: Ubuntu 18.04.2
 - Neovim version: nvim-gtk (candidate) 0.1.1 from Andrey (daa84)
 - Neovim-Gtk build version: snap

Further details:

sudo snap install --edge nvim-gtk
nvim-gtk (candidate) 0.1.1 from Andrey (daa84) installed
Channel edge for nvim-gtk is closed; temporarily forwarding to candidate.

$ nvim-gtk
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
/snap/nvim-gtk/2/bin/desktop-launch: line 231:  5517 Segmentation fault      (core dumped) $RUNTIME/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $GDK_PIXBUF_MODULE_FILE

/snap/nvim-gtk/2/bin/desktop-launch: line 254:  5522 Segmentation fault      (core dumped) $RUNTIME/usr/lib/$ARCH/libgtk-3-0/gtk-query-immodules-3.0 > $GTK_IM_MODULE_FILE

(.:5450): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap (core dumped)

**Comment by daa84** [comment]
sorry, snap is not more supported.

**Comment by jean** [comment]
Aww fiddlesticks, I just hit this too. Could https://snapcraft.io/nvim-gtk maybe be removed from the store?
