### ISSUE TITLE
Clipboard on Wayland

### ISSUE THREAD

**Issue by travankor** [daa84/neovim-gtk#205]
Clipboard on Wayland doesn't seem to work. Tested on KDE Wayland 5.16.3. GVim works fine.

**Comment by mcepl** [comment]
Not correct, with Gnome 3.32.2 and ``$XDG_SESSION_TYPE`` showing ``wayland``, I get perfectly working clipboard (both ``+`` and ``*`` registers).

**Comment by travankor** [comment]
You are correct. This a KDE problem. I tested on sway now, and it works.
