### ISSUE TITLE
statuslne buffer information

### ISSUE THREAD

**Issue by Aletz-Arce** [daa84/neovim-gtk#216]
Hi,
In my setup i can't see buffer information in the top of nvim, statusline are displaced up top.
How to fix that ?
![Captura de pantalla de 2019-10-04 19-24-13](https://user-images.githubusercontent.com/5661038/66246869-52a1b100-e6dd-11e9-90d2-e8d4b797757d.png)

**Comment by daa84** [comment]
https://github.com/daa84/neovim-gtk/wiki/Configuration#options
disable external tab line

**Comment by Aletz-Arce** [comment]
> [daa84/neovim-gtk/wiki/Configuration#options](https://github.com/daa84/neovim-gtk/wiki/Configuration#options)
> disable external tab line

Thank a lot
