### ISSUE TITLE
Multiple rendering issues

### ISSUE THREAD

**Issue by ford-prefect** [daa84/neovim-gtk#220]
**Describe the bug**
I see a number of rendering problems with nvim-gtk, while scrolling, using Ctrl-P, and moving the cursor. Screenshots below:

![Scrolling with page-up key](https://user-images.githubusercontent.com/594179/67286792-a1ca4d00-f4f7-11e9-8d50-d10eb6b68e9f.png)

![Trying to use Ctrl-P plugin](https://user-images.githubusercontent.com/594179/67286794-a262e380-f4f7-11e9-8c01-12d8b6da5db7.png)

![Moving the cursor with arrow keys](https://user-images.githubusercontent.com/594179/67286796-a262e380-f4f7-11e9-8c2d-0367cb903a25.png)

**Technical information (please complete the following information):**
 - OS: Fedora 31 Beta (also saw on Fedora 30)
 - Neovim version: 0.4.2 (also saw on 0.3.x)
 - Neovim-Gtk build version: built from git, sha: 3ace1d29bb4e9586c38848899298fa342668daed (also tried doing a `cargo update`)

**Comment by smolck** [comment]
What's `pango` version are you using? This looks to me like it might be a duplicate of #208.

**Comment by ford-prefect** [comment]
I'm on `pango-1.44.6`. It does seem to be a duplicate indeed, so going to close this now.
