### ISSUE TITLE
Cleanup failed build, including downloaded dependencies

### ISSUE THREAD

**Issue by felixendres** [daa84/neovim-gtk#221]
Hi,
I tried installing neovim-gtk from source on Ubuntu 16.04. I get an error during "make":

> error: failed to run custom build command for `gdk-sys v0.8.0`
> Caused by:
  process didn't exit successfully: `/home/me/Code/neovim-gtk/target/debug/build/gdk-sys-ac97e9fc22e7264d/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "gdk-3.0" "gdk-3.0 >= 3.22"` did not exit successfully: exit code: 1
--- stderr
Requested 'gdk-3.0 >= 3.22' but version of GDK is 3.18.9

I now would like to get my machine back to the prior state, but I don't know how to remove all the stuff that was downloaded during the attempted installation. I know how to do that for the debian packages, but I don't know about the stuff downloaded by the make-file. Is it all within the cloned repository, so that "rm -r" will suffice?

Could you please give me instructions for uninstallation, so I can reinstate the prior state of my system?

Thanks.

**Comment by XVilka** [comment]
```sh
make clean; git clean -xdf
```
I should note that your Ubuntu version is very old, and for many Rust-based programs it can be a problem, the latest LTS version is [18.04 Bionic Beaver](https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_18.04_LTS_(Bionic_Beaver)), while latest normal release is [19.10 Eoan Ermine](https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_19.10_(Eoan_Ermine)). Thus I highly recommend to upgrade.

**Comment by felixendres** [comment]
Thanks. Didn't print any message, so I hope it worked.
Can't update due to company policy.
