### ISSUE TITLE
Redraw issues and very slow command line with Fedora 31, Gnome 3.34.1

### ISSUE THREAD

**Issue by sebastien** [daa84/neovim-gtk#222]
I updated to Fedora 31 yesterday and I am experiencing weird issues:
- When entering command mode `:`, I can type but nothing gets displayed. The commands are executed, though (I can type `:q!` and hit enter to quit).
- It seems that the UI redrawing is affected, as illustrated in the screenshot below, some repaints don't happen. If I move away from the window and refocus, repaint works as expected
- If I run neovim with an argument (like `./target/release/nvim-gtk README.md`) the initial load is super slow (5-10 seconds)

![image](https://user-images.githubusercontent.com/14598/67901031-a0b9af80-fbca-11e9-84a4-3363c365d4a8.png)
 
I did ran `rustup` (nightly), and did a clean checkout and build of neovim-gtk `3ace1d29bb4e9586c38848899298fa342668daed`. I imagine it's due to some API changes in GTK's font rendering?

**Comment by XVilka** [comment]
Yes, I can confirm this issue as well.

**Comment by keeferrourke** [comment]
I can also confirm this issue on GNOME 3.34 with Fedora 31, as of https://github.com/daa84/neovim-gtk/commit/3ace1d29bb4e9586c38848899298fa342668daed built freshly with the nightly rust toolchain.

**Comment by ford-prefect** [comment]
Duplicate of #208

**Comment by sebastien** [comment]
Closing as duplicate.
