### ISSUE TITLE
Compose key does not work

### ISSUE THREAD

**Issue by felmab** [daa84/neovim-gtk#25]
Thanks for writing neovim-gtk! I was really pleased to see that it both supports ligatures and accepts Pragmata Pro as a font, which is not declared as monospaced and thus rejected by other programs (like neovim-qt).

I noticed the compose key does not work, do you think this could be fixed? For the record, a compose key is a dead key used to type characters not present on the keyboard. For instance compose + e + ' will insert an accentuated 'e' ('é'), more on this [here](https://en.wikipedia.org/wiki/Compose_key). I have no issues with other GTK applications.

**Comment by daa84** [comment]
Looks like same as #6

**Comment by felmab** [comment]
Right, I had not realized #6 was a dead key issue too.

**Comment by daa84** [comment]
Duplication of #6
