### ISSUE TITLE
Trouble with vim-devicons

### ISSUE THREAD

**Issue by felmab** [daa84/neovim-gtk#26]
Devicons are not rendered properly (see attached screenshots). I know these are double width characters not obvious to deal with, do you think this could be fixed?

![nvim-gtk](https://user-images.githubusercontent.com/34012743/33432137-23480b34-d5d7-11e7-92b4-8f307c740352.png)
![nvim-gtk-2](https://user-images.githubusercontent.com/34012743/33432138-23610bc0-d5d7-11e7-8697-9d9fe23a10a3.png)

**Comment by daa84** [comment]
Can you provide screenshot with good rendering? Did i understand right that icons cut?

**Comment by felmab** [comment]
Sure, this is in terminal nvim. You should indeed see a whole elephant for PHP files, not just half of it.

![nvim](https://user-images.githubusercontent.com/34012743/33476705-389c0f42-d683-11e7-8cc4-0fe530e3bb69.png)

**Comment by felmab** [comment]
Thanks!
