### ISSUE TITLE
Persistent configuration

### ISSUE THREAD

**Issue by felmab** [daa84/neovim-gtk#27]
I successfully followed [these instructions](https://github.com/daa84/neovim-gtk/wiki/Configuration#font-settings) to configure the font and disable the external tabline. I was unable to add these declarations in $HOME/.config/nvim/ginit.vim so as they are automatically fired when neovim-gtk is open, though. Could you give me some pointers?

**Comment by daa84** [comment]
Can't say, for me it just works 😄 
Can you provide some details? font and tabline does not work both?

**Comment by felmab** [comment]
I does work when I call these directly from Vim command line, but I get an error when I put them in ~/.config/nvim/ginit.vim:
<pre>if exists('g:GtkGuiLoaded')
    call rpcnotify(1, 'Gui' 'Font', 'PragmataPro 12')
endif</pre>
![nvim_error](https://user-images.githubusercontent.com/34012743/33478968-7895105a-d68b-11e7-8f3d-889f80ba3ff2.png)

**Comment by daa84** [comment]
'Gui', 'Font', you forget ','

**Comment by felmab** [comment]
Correct! Busy week ^^
