### ISSUE TITLE
Impossible to install neovim-gtk on Ubuntu 22.04 (dependency problem with package 'fragile')

### ISSUE THREAD

**Issue by 6000years** [daa84/neovim-gtk#271]
After a fresh install of rust and a git clone of neovim-gtk I can make neovim-gtk but `cargo install --path .` fails with

```
  Installing nvim-gtk v0.3.0 (/home/user1/github/neovim-gtk)
    Updating crates.io index
error: failed to compile 'nvim-gtk v0.3.0 (/home/user1/github/neovim-gtk)', intermediate artifacts can be found at '/home/user1/github/neovim-gtk/target'

Caused by:
  failed to select a version for the requirement 'fragile = "^0.3"'
  candidate versions found which didn't match: 1.2.1, 1.2.0
  location searched: crates.io index
  required by package 'gio v0.7.0'
      ... which satisfies dependency 'gio = "^0.7.0"' of package 'nvim-gtk v0.3.0 (/home/user1/github/neovim-gtk)'
```
`make install` fails with the same error
Running neovim-gtk from the target/release directory seems to work (at least it starts up ok)

The build process reports that it is building fragile 0.3.0 ("Compiling fragile v0.3.0 ") and this seems to work, ie no error message is reported.

OS: Ubuntu 22.04
neovim-gtk version: v0.2.0-76-gc036492
git build ref: c036492  Merge pull request #260 from licynthiax/main
(but git reset to v0.2.0 had the same problem, just with a different version of fragile)

**Comment by theHamsta** [comment]
Please try `cargo install --path . --locked`. I personally use this fork https://github.com/Lyude/neovim-gtk

Locked has the risk of
```
warning: package `fragile v0.3.0` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
```
so using out-dated packages (security issues?). Normal install will try to use the latest versions of that packages that are sem-ver compatible.

**Comment by 6000years** [comment]
Thanks. That makes the install program work, with the warning you gave, but it's very little use. It doesn't install to any sensible directory (uses /root/.cargo/bin) and only the root user can run it.   There's no gnome setup so you can't run it from gnome desktop. So overall this installer is hopeless.
