### ISSUE TITLE
Only lowercase letters can be typed with Cyrillic X11 keyboard layout (only Shift key related)

### ISSUE THREAD

**Issue by unclechu** [daa84/neovim-gtk#29]
I can't type any capital Cyrillic letter, only lowercase letters can be typed. But interesting detail is that it happens only when I press Shift key, if I turn Caps Lock mode on I can do it as expected.

**Comment by daa84** [comment]
Looks like changes from #6 kill something

**Comment by unclechu** [comment]
@daa84 Oh, I just realized that latest master fixes it, now it's working with 778884e.

**Comment by unclechu** [comment]
Probably opposite is happened, changes from #6 fixed this.

**Comment by unclechu** [comment]
I should mention commit where this could be reproduced to reduce misunderstandings.
