### ISSUE TITLE
Cannot enter lesser then character

### ISSUE THREAD

**Issue by babba22** [daa84/neovim-gtk#3]
As per title, I am not able to enter the lesser then character ('<') when in insert mode, it simply does nothing. I can enter the greater then character ('>') though

**Comment by daa84** [comment]
I can't reproduce, but think i know problem source :) fix it, can you check? Also what OS/neovim version do you use?

**Comment by babba22** [comment]
Archlinux, neovim 0.1.7-3.
Sadly, I still can't enter '<'. How can I help you? No enough coding skill, sorry... D:

**Comment by daa84** [comment]
Ok, I add log facility to program, so can you do next steps:
update application
run it as `RUST_LOG=nvim_gtk::input,nvim_gtk::shell cargo run`
this will enable logging of all entered keys, for my case it looks like this:
```
DEBUG:nvim_gtk::input: keyval -> <
DEBUG:nvim_gtk::shell: nvim_input -> <lt>
DEBUG:nvim_gtk::input: keyval -> >
DEBUG:nvim_gtk::shell: nvim_input -> >
```
And past result for '<' key.
Thanks.

**Comment by babba22** [comment]
Here you are:

```
DEBUG:nvim_gtk::input: keyval -> >
DEBUG:nvim_gtk::shell: nvim_input -> >
DEBUG:nvim_gtk::shell: nvim_input -> <
```

Hope it helps!

**Comment by daa84** [comment]
Ok, find problem source, must work now :)
thanks for report

**Comment by babba22** [comment]
You're welcome! Thank you for this neovim GUI! 👍
