### ISSUE TITLE
Possible to show Buffer list? (As in vim-airline)?

### ISSUE THREAD

**Issue by ammen99** [daa84/neovim-gtk#33]
![screenshot-2017-12-08-09 15 33](https://user-images.githubusercontent.com/6287487/33755187-5febf57e-dbf8-11e7-85af-bdb42c685960.png)

See the first "line", it is a list of the currently opened buffers(this is terminal neovim). In the GUI they are not visible(and other NVIM GUIs I've tested show them)

**Comment by daa84** [comment]
You can try to disable external tabline, maybe this helps https://github.com/daa84/neovim-gtk/wiki/Configuration#options

**Comment by ammen99** [comment]
thanks, this seems to work. The first time I read about this option I thought that it wouldn't affect the "internal" tabline, but it does!
