### ISSUE TITLE
Neovim config not loaded

### ISSUE THREAD

**Issue by streichgeorg** [daa84/neovim-gtk#4]
My `init.vim` is located at `/home/computer/.config/nvim`. Keymappings and theme don't get loaded when running with `cargo run --release`. OS is Ubuntu 16.04. 

Edit: Some keymappings actually work, but those with `<F1>`, `<F2>` etc. don't work.

**Comment by daa84** [comment]
Does it mean init.vim loaded? Only some keymappings does not work?
please provide not working keymap examples. Maybe there is some problem with input processing.

**Comment by streichgeorg** [comment]
I'm sorry, I should have done some more research before posting here. My init.vim was actually loaded, it was just some mappings not working and my theme not being displayed. Anyways the mappings are fixed now so thank you for this.

**Comment by daa84** [comment]
Ok, then i close this issue. Thanks for report.

About theme issue, if it mapped to gui like has("gui_running") it will not work. To set colorscheme only for gui mode please use ginit.vim. Or maybe this is some theme problem.
