### ISSUE TITLE
Positioning the ext_cmdline in the upper middle of the window

### ISSUE THREAD

**Issue by urandom** [daa84/neovim-gtk#44]
Hi,

I tried out the ext_cmdline branch to see what the upcoming command line would look like, so please disregard this issue if you think it's not relevant.

The current implementation shows the command line as a popup, positioned next to the cursor, and that's confused me a bit since the commands do not tend to be relevant to the character under the cursor (they are usually related to the document or the vim instance itself).

Would it be possible to instead implement the popup in the upper-center part of the window itself. That's how it usually is in other editors and IDEs (vscode, sublime text and intellij come to mind, with what constitutes as an equivalent of a command prompt), with the equivalent of a wildmenu appearing below the popup prompt as a list.

**Comment by daa84** [comment]
This is just idea, i don't know how ending result will look like 😄 
My idea is: user look at cursor when input something in editor, then enter some command - and it continue at cursor position as a bit different user input. I want to check how it feels, if it ok or not then make decision.
