### ISSUE TITLE
Completion Popup Menu does not hilite current selection

### ISSUE THREAD

**Issue by Dasmark** [daa84/neovim-gtk#45]
In regular neovim, when the popup completion menu appears, the selected entry is hilited according to PmenuSel. I understand that this probably cannot be done with neovim-gtk, but currently there is no hilite or frame or whatsoever at all, which makes it impossible to navigate the completion list.

**Comment by daa84** [comment]
Currently highlight is exists and works for me. But it implemented as some css style change inside application, maybe this does not work for some themes... can't say.

**Comment by Dasmark** [comment]
Doesn't work for none of the vim themes. Or do you mean GTK-themes?

**Comment by daa84** [comment]
Yes, I mean gtk theme

**Comment by Dasmark** [comment]
So I tried 5 different GTK themes and for none of them hiliting worked. Interestingly, the background-color of the popup gets styled according to the vim colorscheme and *not* to the GTK-theme. Which GTK-theme do you use where this works for?

**Comment by daa84** [comment]
I use ubuntu default theme. Currently style for selected item looks like this 
```css
.view {color: {}; background-color: {};}
```
maybe something wrong with this...
code is here https://github.com/daa84/neovim-gtk/blob/3985f215cef2759cde7f323c25ad61f182b3c28c/src/popup_menu.rs#L172

**Comment by Dasmark** [comment]
If I comment out that whole `gtk::CssProviderExt::load_from_data()` block, the selected popup entry get hilited according to the system GTK theme. If I replace `bg.to_hex()` with `"red"` it gets a red background. So I'm assuming, that
```
166         let bg = color_model.pmenu_bg_sel();                                                                                                             
167         let fg = color_model.pmenu_fg_sel();                   
```

**Comment by daa84** [comment]
what version of neovim do you use? is it > 0.2.1?
Is there some error messages in console when you start application or change colorscheme in neovim?

**Comment by Dasmark** [comment]
Currently using 0.2.1

If I dump `bg` and `fg` I get the explicit values for the regular fg and bg, not the PMenu ones

**Comment by Dasmark** [comment]
Okay, compiled 0.2.2 manually and it works. Sorry for bothering you :o(
