### ISSUE TITLE
Hiding the title bar

### ISSUE THREAD

**Issue by theduke** [daa84/neovim-gtk#48]
The title bar is ginourmous. 

A setting to hide it completely would be much appreciated.

**Comment by wezm** [comment]
Try setting `NVIM_GTK_NO_HEADERBAR=1`

https://github.com/daa84/neovim-gtk/wiki/Configuration#environment-variables

**Comment by theduke** [comment]
Cool, thanks.

**Comment by nbicalcarata** [comment]
Sorry, but i don't know where to place this setting :(

**Comment by daa84** [comment]
This is environment variable

**Comment by nbicalcarata** [comment]
Oh god, im already checking my dotfiles, i edited my .bashrc, but im using zsh XD, it's working now :)

**Comment by qazip** [comment]
Setting the environment variables works when nvim-gtk is called from terminal. However, when calling from the .desktop entry, it doesn't seem to work. Any ideas @daa84?

**Comment by theduke** [comment]
@qazip put the variable in `~/.profile` which is loaded by X.

(Note: you'll have to restart your WM / start a new login session for this to take effect)

**Comment by wezm** [comment]
Alternatively you can create a copy of the desktop entry and add the environment variable to it.

1. Copy the desktop entry from `/usr/share/applications` to `~/.local/share/applications`
1. Edit the copy and change the `Exec` line to something like: `Exec=env NVIM_GTK_NO_HEADERBAR=1 nvim-gtk`
