### ISSUE TITLE
GUI configuration as in Neovim Qt

### ISSUE THREAD

**Issue by msehnout** [daa84/neovim-gtk#5]
I'm using [Neovim Qt](https://github.com/equalsraf/neovim-qt) as my primary editor, but I'd like to try neovim-gtk as well, but the configuration file is not compatible (I have to move the config file every time I want to try gtk and then move it back). What about using the same configuration syntax, so it can be used side-by-side?

https://github.com/equalsraf/neovim-qt/blob/master/src/gui/runtime/plugin/nvim_gui_shim.vim

**Comment by daa84** [comment]
Ok, it's good idea i think, but i don't want to implement all this commands, maybe only map GuiFont and leave all over commands empty to make it compatible with neovim-qt? Is any other useful command here?

**Comment by msehnout** [comment]
Not sure. I use just the font. It depends how you plan to implement it.

**Comment by msehnout** [comment]
Thanks, it works fine now. 👍

**Comment by daa84** [comment]
Only GuiFont command implemented, also g:GtkGuiLoaded falg added, so it is possible to test in config if nvim-gtk is running.
Thanks for report
