### ISSUE TITLE
Remember previous window size

### ISSUE THREAD

**Issue by vijaygopal1234** [daa84/neovim-gtk#52]
My monospace font is pretty big and it results in the text wrapping oddly everytime I open neovim. Is there a way for neovim to remember what size I set it last and open to that?

**Comment by daa84** [comment]
Currently there is no such function in application.

**Comment by vijaygopal1234** [comment]
[This link](https://wiki.gnome.org/HowDoI/SaveWindowState) makes it sound like it is possible.

**Comment by daa84** [comment]
yes, it's possible, just a question of time :smile:

**Comment by daa84** [comment]
Done :smile:

**Comment by vijaygopal1234** [comment]
Oh wow! I didn't expect you to implement it that fast. Thanks so much!
