### ISSUE TITLE
Running :Denite hangs and crashes ui

### ISSUE THREAD

**Issue by nbicalcarata** [daa84/neovim-gtk#59]
Denite works fine in neovim-qt and gnome-terminal, here's the terminal output:

`Event set_icon([String(Utf8String { s: Ok("") })])
Event set_title([String(Utf8String { s: Ok("nvimrc (~/dotfiles) - NVIM") })])
ERROR 2018-02-20T07:02:19Z: nvim_gtk::nvim::ext: Unknown error type: Wait timeout (nvim_get_hl_by_name)
ERROR 2018-02-20T07:02:29Z: nvim_gtk::nvim::ext: Unknown error type: Wait timeout (nvim_get_hl_by_name)
ERROR 2018-02-20T07:02:39Z: nvim_gtk::nvim::ext: Unknown error type: Wait timeout (nvim_get_hl_by_name)
ERROR 2018-02-20T07:02:49Z: nvim_gtk::nvim::ext: Unknown error type: Wait timeout (nvim_get_hl_by_name)
ERROR 2018-02-20T07:02:59Z: nvim_gtk::nvim::ext: Unknown error type: Wait timeout (nvim_get_hl_by_name)
ERROR 2018-02-20T07:03:09Z: nvim_gtk::nvim::ext: Unknown error type: Wait timeout (nvim_get_hl_by_name)
Event set_icon([String(Utf8String { s: Ok("") })])
Event set_title([String(Utf8String { s: Ok("[denite] (~/dotfiles) - NVIM") })])
Event set_icon([String(Utf8String { s: Ok("") })])
Event set_title([String(Utf8String { s: Ok("nvimrc (~/dotfiles) - NVIM") })])
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'Can't join dispatch thread: Any', src/libcore/result.rs:906:4
thread 'main' panicked at 'Error run input command to nvim: GenericError("Wait timeout (nvim_input)")', src/libcore/result.rs:906:4
Uncaught panic, exiting
[1]    10255 abort (core dumped)  nvim-gtk
`

**Comment by unclechu** [comment]
@nbicalcarata Please, specify commit hash.

**Comment by unclechu** [comment]
@daa84 I have this bug too, on f9b20db. When I try to open [Denite](https://github.com/Shougo/denite.nvim) window app I got *neovim-gtk* frozen for about 30 second or a minute and then it works, but I have the same freeze when I close *Denite* window.

I just realized I have it too with 8bf342e and even with 0f377b7. But I'm sure yesterday it was working fine.

**Comment by nbicalcarata** [comment]
I have set the flag frozen in vim plug, with Denite commit [a5bd4d](a5bd4d15f44e5de8f695b3d720ea1ded469ae93b), until this is fixed.

`Plug 'Shougo/denite.nvim', {'commit' : 'a5bd4d15f44e5de8f695b3d720ea1ded469ae93b', 'frozen' : '1'}`

**Comment by unclechu** [comment]
@nbicalcarata you're right, this commit (of *Denite*) doesn't have this problem, and next commits even have some issues with TUI, see Shougo/denite.nvim/issues/451 I just created.

**Comment by unclechu** [comment]
@daa84 I think this is more bug of *Denite* than *neovim-gtk*. But still it is strange that such just blinking (I guess I could say *redrawing whole screen*) in TUI causes that huge freeze in *neovim-gtk*.

**Comment by unclechu** [comment]
@nbicalcarata This is fixed in *Denite* by Shougo/denite.nvim@ca23187

**Comment by nbicalcarata** [comment]
Great! Thanks
