### ISSUE TITLE
[Feature request] File browser

### ISSUE THREAD

**Issue by babba22** [daa84/neovim-gtk#75]
At the moment I have no idea how files and folders are ordered in the file browser; it would be nice to use alphabetical order (even better, to give the user the choice on how to order them)

**Comment by daa84** [comment]
For me currently it is alphabetical order. But it take case into account.

**Comment by babba22** [comment]
I opened this issue because of this :sweat_smile: :

![screenshot from 2018-03-21 11-53-38](https://user-images.githubusercontent.com/14874690/37706098-860c630e-2cfe-11e8-9a53-fcac682d6182.png)

**Comment by christopher-l** [comment]
Yup, that is not supposed to happen. :D

I think sorting got confused by different permissions.

**Comment by babba22** [comment]
Great! Now it works :+1: 
Thanks a lot
