### ISSUE TITLE
Can't open multiple files in one instance from command line

### ISSUE THREAD

**Issue by bertoldia** [daa84/neovim-gtk#78]
When I try to open multiple files from the command line like so:
```
nvim-gtk file-a file-b file-c
```
I'd expect them to all be opened in the same neovim-gtk instance. This is how neovim, vim, gvim (aka vim-gtk) and pretty much every other editor work. Instead, with neovim-gtk each file is opened in it's own instance.

Using v0.1.1-3 on Arch.

**Comment by daa84** [comment]
did #74 fix this issue?

**Comment by bertoldia** [comment]
Yes!!! Thanks, and sorry for creating a DUP.
