### ISSUE TITLE
Compiling error 

### ISSUE THREAD

**Issue by Zardoz89** [daa84/neovim-gtk#85]
I'm trying to compile the actual head of the repo ( commit e67e03605d61881180c390dbc44b88430ebbd23d ) , and I'm getting this errors on Ubunyu 17.10 : 

```

  Compiling pango v0.4.0
error: use of unstable library feature 'refcell_replace_swap' (see issue #43570)
   --> src/ui.rs:492:19                                                                                                                                      
    |
492 |         self.data.replace(t)
    |                   ^^^^^^^

error[E0599]: no method named `is_ascii` found for type `char` in the current scope
  --> src/input.rs:35:15
   |
35 |         if ch.is_ascii() && !ch.is_alphanumeric() {
   |               ^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           candidate #1: `use std::ascii::AsciiExt;`

error: aborting due to 2 previous errors

error: Could not compile `nvim-gtk`.
```

**Comment by wezm** [comment]
The [documentation suggests that RefCell replace has been stable since rust 1.24](https://doc.rust-lang.org/std/cell/struct.RefCell.html#method.replace). Sounds like you need to update your rust compiler.

**Comment by daa84** [comment]
Yes, please use latest stable rust

**Comment by metalelf0** [comment]
As a side note, on Ubuntu, make sure `sudo` commands use the same `rustc` version of your user. Running `sudo -E env "PATH=$PATH" make install` will preserve your user `$PATH` so you'll be sure you'll use the same rustc and not the one found in `/usr/bin`, as `sudo` commands don't load a shell (and `.profile`) but use the `secure_path` directive in `/etc/sudoers` file.

**Comment by Zardoz89** [comment]
Humm... Rust compiler version looks that evolves quickly, not ?? I installed rust like a few month ago. Compared against c++ or DLang, it moves very quickly
