### ISSUE TITLE
What actually happens on <ScrollWheelUp>/<ScrollWheelDown>?

### ISSUE THREAD

**Issue by unclechu** [daa84/neovim-gtk#86]
I have my own maps for these events:
https://github.com/unclechu/neovimrc/blob/91709e60bc3cb9d5713c5f8024554800da3ad053/ginit.vim#L56-L57
It works but standard action is also triggered (scrolling by pages), why it isn't overwritten by my own maps? Is neovim-gtk handle mouse wheel events differently? Could I suppress default behavior?

Related commit: d8d33ed

**Comment by daa84** [comment]
nvim-gtk just send events from mouse to neovim, nothing more.

**Comment by daa84** [comment]
Looks like bug in neovim https://github.com/neovim/neovim/issues/6211

**Comment by unclechu** [comment]
I'm closing it for now since it isn't `neovim-gtk`'s bug.
