### ISSUE TITLE
[Feacture request] Read from stdin

### ISSUE THREAD

**Issue by bertinatto** [daa84/neovim-gtk#87]
First of all, thank you so much for neovim-gtk! I really hope the project keeps going.

Right now I only miss 1 thing to make neovim-gtk my default editor, and that's the ability to do:

`echo blah | nvim-gtk -`

I'd love to be able to do that.

**Comment by daa84** [comment]
Interesting in typical use case for this feature?
Current implementation does not require `-` argument.

**Comment by daa84** [comment]
Merged to master
