### ISSUE TITLE
Problems with font anti-aliasing

### ISSUE THREAD

**Issue by mcepl** [daa84/neovim-gtk#88]
With Fira Code Medium font, it seems to me that letters are a way smoother when opening the document in gnome-terminal and console neovim than with neovim-gtk. See the screenshot below

![screenshot from 2018-04-13 13-55-29](https://user-images.githubusercontent.com/198999/38733668-124879f8-3f23-11e8-8c6c-dc75731e914b.png)

Left is neovim-gtk and right is the console neovim in gnome-terminal. Using RHEL-7 with gtk3-3.22.26-3.el7.x86_64, freetype-2.4.11-15.el7.x86_64, pango-1.40.4-1.el7.x86_64, and neovim-0.2.2-1.0.8.gitd49c1dda8.el7.centos.x86_64. neovim-gtk is my own build from commit 25921d2.

**Comment by daa84** [comment]
Don't know what it can be. I don't do any special tweaking of font rendering.

**Comment by daa84** [comment]
@mcepl can you try with commit bda35efe8810f7cfab9c56778f9dd7cb066425c2 ?

**Comment by mcepl** [comment]
Seems better. Thanks.
