### ISSUE TITLE
Crashes and not properly resized

### ISSUE THREAD

**Issue by unclechu** [daa84/neovim-gtk#89]
I consider it is related to https://github.com/daa84/neovim-gtk/issues/58

So it still doesn't resize properly if I change window size right in time last change isn't complete yet. Sometimes when I do it it also crashes.

I recorded a screencast to demonstrate it: https://youtu.be/k28p-veDPV0

**Comment by daa84** [comment]
Fixed problem with resize, 
can't reproduce crash If it still crashes please create new issue with stack trace if possible :smiley:

**Comment by unclechu** [comment]
I confirm it is fixed.
