### ISSUE TITLE
Use mouse to make visual selection

### ISSUE THREAD

**Issue by jgosmann** [daa84/neovim-gtk#90]
In gvim the mouse can be used to make a visual selection. It would be nice if this worked in nvim-gtk too. At the moment clicking and dragging will move the cursor, but does not create a visual selection.

**Comment by wezm** [comment]
NeovimGtk works as you describe for me. I'm using a recent master version on Arch Linux. What platform are you using?

![peek 2018-04-20 09-45](https://user-images.githubusercontent.com/21787/39023686-88c1a2b0-447f-11e8-9071-9111f5301b50.gif)

**Comment by kirillrdy** [comment]
@wezm thanks for the animation,
however I can confirm that I have same issue,
this is latest master, xorg, FreeBSD-12, Gnome-3.28 if this helps

**Comment by jgosmann** [comment]
Latest master as well (b44799bef7), on [Chakra Linux](https://www.chakralinux.org/) (originally based on Arch I believe). I'm running NeovimGtk under KDE with gtk versions:
* gtk3 3.22.26-2
* gtk2 2.24.32-1
My nvim is v0.2.3-966-gd49c1dda8 with patch 1678 from the original Vim applied (that patch is only related to the errorformat setting and should be irrelevant with regards to this issue).

Could there be an interaction with Vim plugins causing this?

Let me know if I can provide any other helpful information.

**Comment by edubxb** [comment]
Same problem here, with the last master (just compiled) on Debian with GNOME (Wayland) and the following versions:

- gtk3 3.22.30
- nvim v0.2.2

**Comment by daa84** [comment]
try `set mouse=a` in config

**Comment by jgosmann** [comment]
That fixes it for me. :)

**Comment by edubxb** [comment]
Fixed!
