### ISSUE TITLE
[Windows] No icon on AppVeyor build

### ISSUE THREAD

**Issue by Anrock** [daa84/neovim-gtk#93]
It would be nice if neovim-gtk had some icon. I've associated all my text files with neovim-gtk and they look like generic executable icon which is confusing. Until there is no branded neovim-gtk icon i guess it's fine to use generic neovim icon like that:
https://commons.wikimedia.org/wiki/File:Neovim-mark-flat.svg
https://commons.wikimedia.org/wiki/Category:Neovim#/media/File:Neovim-mark.svg

**Comment by daa84** [comment]
It already used and installed together with desktop file with `make install`. https://github.com/daa84/neovim-gtk/blob/bda35efe8810f7cfab9c56778f9dd7cb066425c2/Makefile#L21

**Comment by Anrock** [comment]
@daa84 i see, i thought there is no icon at all. 
There is no icon on AppVeyor builds. Renamed issue accordingly.

**Comment by Anrock** [comment]
@daa84 ping

**Comment by Anrock** [comment]
@daa84 ping

**Comment by daa84** [comment]
As i don't know how icons works in windows, it will be helpful to have link to description or link to how to add it appveyor build or rust specific logic. Maybe some rust project already have such function so we can look at it?

So to speedup develop any issue in case you can't provide pr it is better to support it with some info on how to better implement it.
