### ISSUE TITLE
Feature request: OpenType font features configuration

### ISSUE THREAD

**Issue by solbjorn** [daa84/neovim-gtk#94]
Is it possible to implement along with already presented ligations?

For example, I use Iosevka's (https://github.com/be5invis/Iosevka) "PURS" extended ligas and several "stylistic set" touches. Can it be enabled/disabled in Neovim-GTK?

And one more, no plans to make global light/dark GTK theme switch accessible from config, not only env?

**Comment by daa84** [comment]
Looks like easy task as pango support this ([pango_attr_font_features_new](https://developer.gnome.org/pango/stable/pango-Text-Attributes.html#pango-attr-font-features-new)) :smile: 

Question is how it must look like, like addition font attribute? Or maybe better as separate command, so features can be changed without changing font settings.

**Comment by daa84** [comment]
Dark theme switch was implemented with some PR so i don't know why it is env, maybe it produce flickering in case it will be in config, not sure. If you want this feature, please create separate issue for it.

**Comment by solbjorn** [comment]
Yep, sure.

As for font features configurations, a separate command seems more attractive and flexible, e.g. you could manually turn off ligatures at all (<"liga" off, "calt" off>) earlier in config and then change fonts without features setup overriding or loss.

How it looks like now in Atom:

`-webkit-font-feature-settings: "cv17" on, "cv19" on, "cv21" on, "cv23" on, "cv30" on, "cv31" on, "PURS" on;`

**Comment by daa84** [comment]
Merged to master
https://github.com/daa84/neovim-gtk/wiki/Configuration#opentype-features
