### ISSUE TITLE
Feature request: light/dark theme switch in config/with command

### ISSUE THREAD

**Issue by solbjorn** [daa84/neovim-gtk#95]
Neovim-GTK currently allows to switch global theme style only through env variable, would be nice to see a config option for that.
I doubt that there will be any flickering or other glitches of that kind, as many GTK3-apps (GNOME Terminal etc.) have runtime switch and can change theme style on-the-fly.

**Comment by daa84** [comment]
New command to switch dark theme https://github.com/daa84/neovim-gtk/wiki/Configuration#commands

**Comment by baco** [comment]
`:NGPreferDarkTheme on`  doesn't work anymore. In fact having it configured raises an error when launching Neovim-gtk
