### ISSUE TITLE
Bug : Suddenly colorschemes aren broken

### ISSUE THREAD

**Issue by Zardoz89** [daa84/neovim-gtk#96]
The last commits (not hapens on commit bda35ef ) has broken vim colorschemes : 

This happens with monokai-phoenix and with darkblue (included on all vim/neovim) color scheme

To reproduce : 
```
" Color mode
if (has("termguicolors"))
  set termguicolors       " TrueColor!
else
  set t_Co=256            " 256 color mode in term
endif

set background=dark
" colors monokai-phoenix
colors darkblue

```

Monokai-phoenix:
![monokai-phoenix](https://user-images.githubusercontent.com/888483/39697901-e9a1c0f8-51f2-11e8-91c2-cb75d4f0c3db.png)

Darkblue:
![darkblue](https://user-images.githubusercontent.com/888483/39698141-df86583a-51f3-11e8-8aef-70b9cb37bc6a.png)

**Comment by daa84** [comment]
Ah, looks like problem only when `NVIM_GTK_DOUBLE_BUFFER=1`

**Comment by Zardoz89** [comment]
@daa84 It's fixed! Keep happening with the last commit.

**Comment by daa84** [comment]
did you use NVIM_GTK_DOUBLE_BUFFER=1 ?

**Comment by ugopozo** [comment]
I experience this issue with both `NVIM_GTK_DOUBLE_BUFFER` on and off.

**Comment by Zardoz89** [comment]
@daa84 I just try with the last commit and with NVIM_GTK_DOUBLE_BUFFER=1 . Works correctly.
![imagen](https://user-images.githubusercontent.com/888483/39811411-e4f73fd2-5388-11e8-9206-b080ab96af0a.png)

@ugopozo Better try to paste commit hash instead of numbers.

**Comment by daa84** [comment]
@Zardoz89  c56c945f025a9350a8e99ab4b77c447ff35f9966 does change something? NVIM_GTK_DOUBLE_BUFFER=0 does not work?

**Comment by daa84** [comment]
NVIM_GTK_DOUBLE_BUFFER do some small performance impact. Also in my local installation i don't have any problems without NVIM_GTK_DOUBLE_BUFFER, so it is disabled by default 😄 
But maybe it is good idea to enable it.

**Comment by Zardoz89** [comment]
> @Zardoz89 c56c945 does change something? NVIM_GTK_DOUBLE_BUFFER=0 does not work?

Keeps happening.

> NVIM_GTK_DOUBLE_BUFFER do some small performance impact. Also in my local installation i don't have any problems without NVIM_GTK_DOUBLE_BUFFER, so it is disabled by default smile
But maybe it is good idea to enable it.

But, why this happening ? Why disabling/enabling double buffering affect this ? It's related to a Gtk bug ?

**Comment by daa84** [comment]
Looks like gtkdrawingarea surface in some configurations (or gtk version) created without alpha channel. Don't know why.

**Comment by YaLTeR** [comment]
Also started hitting this issue, `NVIM_GTK_DOUBLE_BUFFER=1` seems to fix it.

**Comment by daa84** [comment]
NVIM_GTK_DOUBLE_BUFFER removed with 21e74c7ca7468a53ce1cbb449a19b8144f06836f , must issue must be fixed
